### ISSUE TITLE
Eliminate constant results of function invocation

### ISSUE THREAD

**Issue by jeron-diovis** [codemix/babel-plugin-closure-elimination#24]
Is it possible to make this plugin also turn this:

```js
function foo(xs) {
  return xs.filter(_.property("bar"))
}
```

into this:

```js
var _ref = _.property("bar")

function foo(xs) {
  return xs.filter(_ref)
}
```

?

**Comment by Gvozd** [comment]
1. Your example is not optimize code
In cases from doc function's optimized, because their not need deepest scope, and when their eliiminated, plugin produce shorter scope chain for variable resolving
In your example real function creating located at another file, and scope also at another file
In this position this optimizing is not worked
Also, maybe has small deoptimize - you use _ref from parent scope, and variable resolve chain longer
2. Has no general way for determine that `_.property("bar")` is function
In concrete case may expect, that first arg for `.filter` is function, but in general case this may be wrong

**Comment by jeron-diovis** [comment]
Ok, understood. Thanks for details.

Just wondering. If in described case we would use our own `property` function, located in the same file – would it be better for performance?

**Comment by Gvozd** [comment]
`property` is function that generate and return inner function
inner function eliminated, if possible - this better for performance

But call of `property` not eliminated - that elimination not optimize variable resolving
Also, if `property` is not clean function(return different results on call with same args, or change global state) this transformation may broke your logic, and this auto-transformation prohibited
But if this function clean I recommend eliminate this call manually - it's optimize calling count of `property` function. But this auto-transformation is invloved, and out of scope of this plugin
